name: tanam_care
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0

  # State Management
  provider: ^6.1.1

  # UI Utils & Formatting
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  form_validator: ^2.1.1

  cupertino_icons: ^1.0.6

  # PERBAIKAN DI SINI:
  # Update ke 0.11.0 agar support model TensorFlow terbaru
  tflite_flutter: 0.12.1

  image_picker: ^1.0.7
  image: ^4.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    # Cukup deklarasikan folder atau file spesifik, hindari duplikasi
    - assets/
    # Baris di bawah ini sebenarnya opsional jika 'assets/' sudah di-include,
    # tapi dibiarkan agar lebih spesifik (aman).
    - assets/tomato_model_int8.tflite
    - assets/labels.txt
